name: API documentation

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Publish API documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        id: setup-jdk
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build API documentation
        run: ./gradlew dokkaHtml
      - name: Publish API documentation
        if: success()
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          branch: gh-pages
          folder: build/dokka/html
          clean: true
